name: instruction_serialiser
description: The Dart implementation of the instruction serialiser
version: 0.0.1
homepage: https://github.com/nico151999/instruction_serialiser/tree/main/dart

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  protobuf: ^2.0.1

dev_dependencies:
  test: "^1.20.1"
